###################################
# Airflow - Common Configs
###################################
executor: KubernetesExecutor

postgresql:
  enabled: false

data:
  metadataConnection:
    user: postgres
    pass: tuEyWJzqTd
    protocol: postgresql
    host: airflow-postgresql.airflow.svc.cluster.local 
    port: 5432
    db: postgres
    sslmode: disable

flower:
  enabled: false

redis:
  enabled: false

statsd:
  enabled: false

config:
  kubernetes:
    multi_namespace_mode: True
    delete_worker_pods: "True"
    delete_worker_pods_on_failure: "False"
  webserver:
    web_server_worker_timeout: 300
    workers: 1
  logging:
    logging_level: "DEBUG"

extraEnv: |
  - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
    value: 'True'
  - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE
    value: 'False'

###################################
# Airflow - DAGs Configs
###################################
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true

    repo: https://github.com/rajeshkudaka/task-orchestration.git
    branch: master
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "airflow/dags"
    wait: 60
    containerName: git-sync
    uid: 65533
    extraVolumeMounts: []
    env: []
    resources: {}
